// notes: array of bell numbers (use '-' for no bell)
// Duration in beats: 0.5 = eighth note, 1 = quarter note, 2 = half note, 3 = dotted half, 4 = whole note
// Add lineBreak: true to force a new line after this note (otherwise auto-breaks at 8 beats)
const songs = {
  "Up on the housetop": {
    timeSignature: 4,
    defaultBPM: 110,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1, lineBreak: true },
      {topNote:15,bottomNote:'-',duration:1,word:'Up'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'on'},
      {topNote:17,bottomNote:'-',duration:0.5,word:'the'},
      {topNote:15,bottomNote:'-',duration:1,word:'house-'},
      {topNote:12,bottomNote:'-',duration:1,word:'top'},
      {topNote:8,bottomNote:'-',duration:1,word:'rein-'},
      {topNote:12,bottomNote:'-',duration:1,word:'deer'},
      {topNote:15,bottomNote:'-',duration:2,word:'pause'},
      {topNote:17,bottomNote:'-',duration:1,word:'out'},
      {topNote:17,bottomNote:'-',duration:1,word:'jumps'},
      {topNote:15,bottomNote:'-',duration:1,word:'good'},
      {topNote:12,bottomNote:'-',duration:1,word:'old'},
      {topNote:10,bottomNote:'-',duration:1,word:'san-'},
      {topNote:15,bottomNote:'-',duration:1,word:'ta'},
      {topNote:15,bottomNote:'-',duration:2,word:'claus'},
      {topNote:15,bottomNote:'-',duration:1,word:'down'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'through'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'the'},
      {topNote:17,bottomNote:'-',duration:1,word:'chim-'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'ney'},
      {topNote:12,bottomNote:'-',duration:0.5,word:'with'},
      {topNote:8,bottomNote:'-',duration:1,word:'lots'},
      {topNote:12,bottomNote:'-',duration:1,word:'of'},
      {topNote:15,bottomNote:'-',duration:2,word:'toys'},
      {topNote:17,bottomNote:'-',duration:1,word:'all'},
      {topNote:17,bottomNote:'-',duration:0.5,word:'for'},
      {topNote:17,bottomNote:'-',duration:0.5,word:'the'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'lit-'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'tle'},
      {topNote:12,bottomNote:'-',duration:1,word:'ones'},
      {topNote:10,bottomNote:'-',duration:1,word:'christ-'},
      {topNote:15,bottomNote:'-',duration:1,word:'mas'},
      {topNote:8,bottomNote:'-',duration:2,word:'joys'},
      {topNote:13,bottomNote:'-',duration:1,word:'ho'},
      {topNote:13,bottomNote:'-',duration:1,word:'ho'},
      {topNote:17,bottomNote:'-',duration:2,word:'ho'},
      {topNote:15,bottomNote:'-',duration:1,word:'who'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'would-'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'nt'},
      {topNote:12,bottomNote:'-',duration:2,word:'go'},
      {topNote:10,bottomNote:'-',duration:1,word:'ho'},
      {topNote:10,bottomNote:'-',duration:1,word:'ho'},
      {topNote:13,bottomNote:'-',duration:2,word:'ho'},
      {topNote:12,bottomNote:'-',duration:1,word:'who'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'would-'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'nt'},
      {topNote:8,bottomNote:'-',duration:1,word:'go'},
      {topNote:12,bottomNote:'-',duration:1,word:'-'},
      {topNote:15,bottomNote:'-',duration:1,word:'up'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'on'},
      {topNote:17,bottomNote:'-',duration:0.5,word:'the'},
      {topNote:15,bottomNote:'-',duration:1,word:'house-'},
      {topNote:12,bottomNote:'-',duration:1,word:'top'},
      {topNote:13,bottomNote:'-',duration:1,word:'click'},
      {topNote:15,bottomNote:'-',duration:1,word:'click'},
      {topNote:17,bottomNote:'-',duration:2,word:'click'},
      {topNote:15,bottomNote:'-',duration:1,word:'down'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'through'},
      {topNote:17,bottomNote:'-',duration:0.5,word:'the'},
      {topNote:15,bottomNote:'-',duration:1,word:'chim-'},
      {topNote:15,bottomNote:'-',duration:0.5,word:'ney'},
      {topNote:12,bottomNote:'-',duration:0.5,word:'with'},
      {topNote:10,bottomNote:'-',duration:1,word:'good'},
      {topNote:15,bottomNote:'-',duration:1,word:'saint'},
      {topNote:8,bottomNote:'-',duration:2,word:'nick'},
      ]
  },
  "Angels We Have Heard on High": {
    timeSignature: 4,
    defaultBPM: 90,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1, lineBreak: true },
      // "Angels we have heard on high"
      { topNote: 12, bottomNote: 8, duration: 1, word: 'An-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'gels' },
      { topNote: 12, bottomNote: 7, duration: 1, word: 'we' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'have' },
      { topNote: 15, bottomNote: 10, duration: 1, word: 'heard' },
      { topNote: "-", bottomNote: 7, duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: "-", duration: 0.5, word: 'on' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'high', lineBreak: true },
      // "Sweetly singing o'er the plains"
      { topNote: 12, bottomNote: 8, duration: 1, word: 'Sweet-' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'ly' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'sing' },
      { topNote: 15, bottomNote: 8, duration: 1, word: 'ing' },
      { topNote: 12, bottomNote: 8, duration: 1, word: "o'er" },
      { topNote: "-", bottomNote: 7, duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: "-", duration: 0.5, word: 'the' },
      { topNote: 8, bottomNote: "-", duration: 2, word: 'plains', lineBreak: true },
      // "And the mountains in reply"
      { topNote: 12, bottomNote: 8, duration: 1, word: 'And-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'the' },
      { topNote: 12, bottomNote: 7, duration: 1, word: 'moun-' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'tains' },
      { topNote: 15, bottomNote: 8, duration: 1, word: 'in' },
      { topNote: "-", bottomNote: 10, duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: "-", duration: 0.5, word: 're-' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'ply', lineBreak: true },
      // "Echoing their joyous strains"
      { topNote: 12, bottomNote: 8, duration: 1, word: 'Ech-' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'o-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'ing' },
      { topNote: 15, bottomNote: 8, duration: 1, word: 'their' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'joy' },
      { topNote: "-", bottomNote: 7, duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: "-", duration: 0.5, word: 'ous' },
      { topNote: 8, bottomNote: "-", duration: 2, word: 'strains', lineBreak: true },
      // "Gloria" - fast runs
      { topNote: 15, bottomNote: 8, duration: 1, word: 'Glo' },
      { topNote: '-', bottomNote: 12, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 10, duration: 0.5, word: '-' },
      { topNote: 17, bottomNote: 8, duration: 0.5, word: '-' },
      { topNote: 15, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: 8, duration: 1, word: '-' },
      { topNote: '-', bottomNote: 10, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 8, duration: 0.5, word: '-', lineBreak: true },
      { topNote: 15, bottomNote: 7, duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: 7, duration: 1, word: '-' },
      { topNote: '-', bottomNote: 8, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 7, duration: 0.5, word: '-', lineBreak: true },
      { topNote: 13, bottomNote: 5, duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 8, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: 3, duration: 1.5, word: '-' },
      { topNote: 3, bottomNote: '-', duration: 0.5, word: 'ri-' },
      { topNote: 3, bottomNote: '-', duration: 2, word: 'a', lineBreak: true },
      // "in excelsis Deo"
      { topNote: 8, bottomNote: 3, duration: 1, word: 'in' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'ex' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'cel' },
      { topNote: 13, bottomNote: 8, duration: 1, word: 'sis' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'De' },
      { topNote: 10, bottomNote: 7, duration: 2, word: 'o', lineBreak: true },
      // Second "Gloria"
      { topNote: 15, bottomNote: 8, duration: 1, word: 'Glo' },
      { topNote: '-', bottomNote: 12, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 10, duration: 0.5, word: '-' },
      { topNote: 17, bottomNote: 8, duration: 0.5, word: '-' },
      { topNote: 15, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: 8, duration: 1, word: '-' },
      { topNote: '-', bottomNote: 10, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 8, duration: 0.5, word: '-', lineBreak: true },
      { topNote: 15, bottomNote: 7, duration: 0.5, word: '-' },
      { topNote: 13, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: 7, duration: 1, word: '-' },
      { topNote: '-', bottomNote: 8, duration: 0.5, word: '-' },
      { topNote: '-', bottomNote: 7, duration: 0.5, word: '-', lineBreak: true },
      { topNote: 13, bottomNote: 5, duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 8, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: 3, duration: 1.5, word: '-' },
      { topNote: 3, bottomNote: '-', duration: 0.5, word: 'ri-' },
      { topNote: 3, bottomNote: '-', duration: 2, word: 'a', lineBreak: true },
      // Final "in excelsis Deo"
      { topNote: 8, bottomNote: 3, duration: 1, word: 'in' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'ex' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'cel' },
      { topNote: 13, bottomNote: 8, duration: 1, word: 'sis' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'De' },
      { topNote: 10, bottomNote: 7, duration: 2, word: '-' },
      { topNote: 8, bottomNote: 3, duration: 4, word: 'o' },
      { topNote: "-", bottomNote: "-", duration: 4, word: '-' },
    ]
  },
  "Joy to the world": {
    timeSignature: 2,
    defaultBPM: 75,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1, lineBreak: true },
      // "Joy to the world, the Lord is come"
      { topNote: 17, bottomNote: 9, duration: 1, word: 'Joy' },
      { topNote: 16, bottomNote: 12, duration: 0.75, word: 'to' },
      { topNote: 14, bottomNote: 10, duration: 0.25, word: 'the' },
      { topNote: 12, bottomNote: 9, duration: 1.5, word: 'world,' },
      { topNote: 10, bottomNote: 7, duration: 0.5, word: 'the' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'Lord' },
      { topNote: 7, bottomNote: 4, duration: 1, word: 'is' },
      { topNote: 5, bottomNote: '-', duration: 1.5, word: 'come;', lineBreak: true },
      // "Let earth receive her King!"
      { topNote: 12, bottomNote: '-', duration: 0.5, word: 'Let' },
      { topNote: 14, bottomNote: 10, duration: 1.5, word: 'earth' },
      { topNote: 14, bottomNote: 10, duration: 0.5, word: 're-' },
      { topNote: 16, bottomNote: 7, duration: 1.5, word: 'ceive' },
      { topNote: 16, bottomNote: 10, duration: 0.5, word: 'her' },
      { topNote: 17, bottomNote: 9, duration: 2, word: 'king!', lineBreak: true },
      // "Let ev'ry heart prepare him room"
      { topNote: '-', bottomNote: '-', duration: 1.5, word: '-' },
      { topNote: 17, bottomNote: 9, duration: 0.5, word: 'Let' },
      { topNote: 17, bottomNote: 9, duration: 0.5, word: 'ev-' },
      { topNote: 16, bottomNote: 12, duration: 0.5, word: '-' },
      { topNote: 14, bottomNote: 10, duration: 0.5, word: 'ry' },
      { topNote: 12, bottomNote: 9, duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: 9, duration: 0.75, word: 'hea-' },
      { topNote: 10, bottomNote: 7, duration: 0.25, word: '-' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: '-rt' },
      { topNote: 17, bottomNote: 9, duration: 0.5, word: 'pre-' },
      { topNote: 17, bottomNote: 9, duration: 0.5, word: 'pare' },
      { topNote: 16, bottomNote: 12, duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: 10, duration: 0.5, word: 'him' },
      { topNote: 12, bottomNote: 9, duration: 0.5, word: '-' },
      { topNote: 12, bottomNote: 9, duration: 0.75, word: 'room' },
      { topNote: 10, bottomNote: 7, duration: 0.25, word: '-' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: '-' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: 'And', lineBreak: true },
      // "And Saints and angels sing"
      { topNote: 9, bottomNote: 5, duration: 0.5, word: 'Saints' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: 'and' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: 'an-' },
      { topNote: 9, bottomNote: 5, duration: 0.25, word: 'gels' },
      { topNote: 10, bottomNote: 7, duration: 0.25, word: '-' },
      { topNote: 12, bottomNote: 9, duration: 1.5, word: 'sing' },
      { topNote: 10, bottomNote: 7, duration: 0.25, word: 'And' },
      { topNote: 9, bottomNote: 5, duration: 0.25, word: '-' },
      { topNote: 7, bottomNote: 4, duration: 0.5, word: 'Saints' },
      { topNote: 7, bottomNote: 4, duration: 0.5, word: 'and' },
      { topNote: 7, bottomNote: 4, duration: 0.5, word: 'an-' },
      { topNote: 7, bottomNote: 4, duration: 0.25, word: 'gels' },
      { topNote: 9, bottomNote: 5, duration: 0.25, word: '-' },
      { topNote: 10, bottomNote: 7, duration: 1.5, word: 'sing' },
      { topNote: 9, bottomNote: 5, duration: 0.25, word: 'And' },
      { topNote: 7, bottomNote: 4, duration: 0.25, word: '-', lineBreak: true },
      // "And Saints, and Saints and angels sing"
      { topNote: 5, bottomNote: '-', duration: 0.5, word: 'Saints' },
      { topNote: 17, bottomNote: 9, duration: 1, word: '-' },
      { topNote: 14, bottomNote: 10, duration: 0.5, word: 'and' },
      { topNote: 12, bottomNote: 9, duration: 0.75, word: 'Saints' },
      { topNote: 10, bottomNote: 7, duration: 0.25, word: '-' },
      { topNote: 9, bottomNote: 5, duration: 0.5, word: '-' },
      { topNote: 10, bottomNote: 7, duration: 0.5, word: 'and' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'an-' },
      { topNote: 7, bottomNote: 4, duration: 1, word: 'gels' },
      { topNote: 5, bottomNote: '-', duration: 2, word: 'sing' },
    ]
  },
  "O Come All Ye Faithful": {
    timeSignature: 4,
    defaultBPM: 85,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1, lineBreak: true },
      // "Oh come, all ye faithful"
      { topNote: 10, bottomNote: 5, duration: 1, word: 'Oh,' },
      { topNote: 10, bottomNote: 5, duration: 2, word: 'come,' },
      { topNote: 5, bottomNote: '-', duration: 1, word: 'all' },
      { topNote: 10, bottomNote: 2, duration: 1, word: 'ye' },
      { topNote: 12, bottomNote: 5, duration: 2, word: 'faith-' },
      { topNote: 5, bottomNote: "-", duration: 2, word: 'ful', lineBreak: true },

      // "Joyful and triumphant!"
      { topNote: 14, bottomNote: 5, duration: 1, word: 'Joy-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'ful' },
      { topNote: 14, bottomNote: 5, duration: 1, word: 'and' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'tri-' },
      { topNote: 14, bottomNote: 5, duration: 2, word: 'um-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'phant!', lineBreak: true },
      // "Oh come ye, Oh come ye to Bethlehem"
      { topNote: 10, bottomNote: 2, duration: 1, word: 'Oh,' },
      { topNote: 10, bottomNote: 2, duration: 1, word: 'come,' },
      { topNote: '-', bottomNote: 4, duration: 1, word: '-' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'ye,' },
      { topNote: 7, bottomNote: 4, duration: 1, word: 'Oh,' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'come,' },
      { topNote: 10, bottomNote: 5, duration: 1, word: '-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'ye' },
      { topNote: 14, bottomNote: 5, duration: 1, word: 'to' },
      { topNote: 9, bottomNote: 5, duration: 2, word: 'Beth-' },
      { topNote: 7, bottomNote: 4, duration: 1.5, word: '-' },
      { topNote: 5, bottomNote: '-', duration: 0.5, word: 'le-' },
      { topNote: 5, bottomNote: '-', duration: 3, word: 'hem' },
      { topNote: '-', bottomNote: '-', duration: 1, word: '-', lineBreak: true },
      // "Come, and behold him"
      { topNote: 17, bottomNote: 5, duration: 2, word: 'Come,' },
      { topNote: 15, bottomNote: 7, duration: 0.5, word: 'and' },
      { topNote: '-', bottomNote: 9, duration: 0.5, word: '-' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'Be-' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'hold' },
      { topNote: '-', bottomNote: 9, duration: 1, word: '-' },
      { topNote: 14, bottomNote: 10, duration: 2, word: 'him', lineBreak: true },
      // "Born the King of angels;"
      { topNote: 12, bottomNote: 5, duration: 1, word: 'Born' },
      { topNote: 14, bottomNote: 5, duration: 1, word: 'the' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'King' },
      { topNote: 12, bottomNote: 7, duration: 1, word: 'of' },
      { topNote: 9, bottomNote: 5, duration: 1.5, word: 'an-' },
      { topNote: 7, bottomNote: '-', duration: 0.5, word: '-' },
      { topNote: 5, bottomNote: '-', duration: 1, word: 'gels;', lineBreak: true },
      // "Oh, come, let us adore him;"
      { topNote: 10, bottomNote: 5, duration: 1, word: 'Oh,' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'come,' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'let' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'us' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'a-' },
      { topNote: 10, bottomNote: 5, duration: 2, word: 'dore' },
      { topNote: 5, bottomNote: "-", duration: 1, word: 'him;', lineBreak: true },
      // "Oh, come, let us adore him;"
      { topNote: 14, bottomNote: 5, duration: 1, word: 'Oh,' },
      { topNote: 14, bottomNote: 5, duration: 1, word: 'come,' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'let' },
      { topNote: 14, bottomNote: 5, duration: 1, word: 'us' },
      { topNote: 15, bottomNote: 9, duration: 1, word: 'a-' },
      { topNote: 14, bottomNote: 10, duration: 2, word: 'dore' },
      { topNote: 12, bottomNote: 9, duration: 1, word: 'him;', lineBreak: true },
      // "Oh, come, let us adore him;"
      { topNote: 14, bottomNote: 10, duration: 1, word: 'Oh,' },
      { topNote: 15, bottomNote: 7, duration: 0.5, word: 'come,' },
      { topNote: '-', bottomNote: 9, duration: 0.5, word: '-' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'let' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'us' },
      { topNote: 10, bottomNote: 4, duration: 1, word: 'a-' },
      { topNote: 9, bottomNote: 5, duration: 2, word: 'dore' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'him,' },
      { topNote: 15, bottomNote: 7, duration: 1, word: '-', lineBreak: true },
      // "Christ the Lord."
      { topNote: 14, bottomNote: 5, duration: 2, word: 'Christ' },
      { topNote: 12, bottomNote: 3, duration: 1.5, word: '-' },
      { topNote: 10, bottomNote: 2, duration: 0.5, word: 'the' },
      { topNote: 10, bottomNote: 2, duration: 4, word: 'Lord.' },

    ]
  },
  "Jingle Bells": {
    timeSignature: 4,
    defaultBPM: 100,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1, lineBreak: true },
      { topNote: 3, bottomNote: '-', duration: 1, word: 'Da-' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'shing' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'through' },
      { topNote: 8, bottomNote: '-', duration: 1, word: 'the' },
      { topNote: 3, bottomNote: '-', duration: 3, word: 'snow' },
      { topNote: 3, bottomNote: '-', duration: 0.5, word: 'In' },
      { topNote: 3, bottomNote: '-', duration: 0.5, word: 'a' },
      { topNote: 3, bottomNote: '-', duration: 1, word: 'one' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'horse' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'op-' },
      { topNote: 8, bottomNote: '-', duration: 1, word: 'en' },
      { topNote: 5, bottomNote: '-', duration: 4, word: 'sleigh' },
      { topNote: 5, bottomNote: '-', duration: 1, word: 'o er' },
      { topNote: 13, bottomNote: '-', duration: 1, word: 'the' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'fields' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'we' },
      { topNote: 7, bottomNote: '-', duration: 4, word: 'go' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'lau-' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'ghing' },
      { topNote: 13, bottomNote: '-', duration: 1, word: 'all' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'the' },
      { topNote: 12, bottomNote: '-', duration: 4, word: 'way' },
      { topNote: 3, bottomNote: '-', duration: 1, word: 'bells' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'on' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'bob-' },
      { topNote: 8, bottomNote: '-', duration: 1, word: 'tails' },
      { topNote: 3, bottomNote: '-', duration: 4, word: 'ring' },
      { topNote: 3, bottomNote: '-', duration: 1, word: 'ma-' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'king' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'spi-' },
      { topNote: 8, bottomNote: '-', duration: 1, word: 'rits' },
      { topNote: 5, bottomNote: '-', duration: 3, word: 'bright' },
      { topNote: 5, bottomNote: '-', duration: 1, word: 'what' },
      { topNote: 5, bottomNote: '-', duration: 1, word: 'fun' },
      { topNote: 13, bottomNote: '-', duration: 1, word: 'it' },
      { topNote: 12, bottomNote: '-', duration: 1, word: 'is' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'to' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'ride' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'and' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'sing' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'a' },
      { topNote: 17, bottomNote: '-', duration: 1, word: 'slei-' },
      { topNote: 15, bottomNote: '-', duration: 1, word: 'ghing' },
      { topNote: 13, bottomNote: '-', duration: 1, word: 'song' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'to-' },
      { topNote: 8, bottomNote: '-', duration: 2, word: 'night' },
      { topNote: 15, bottomNote: '-', duration: 2, word: 'oh' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'gle' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'bells' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'gle' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'bells' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 15, bottomNote: 12, duration: 1, word: 'gle' },
      { topNote: 8, bottomNote: 3, duration: 1.5, word: 'all' },
      { topNote: 10, bottomNote: 7, duration: 0.5, word: 'the' },
      { topNote: 12, bottomNote: 8, duration: 4, word: 'way' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'oh' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'what' },
      { topNote: 13, bottomNote: 10, duration: 1.5, word: 'fun' },
      { topNote: 13, bottomNote: 10, duration: 0.5, word: 'it' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'is' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'to' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'ride' },
      { topNote: 12, bottomNote: 8, duration: 0.5, word: 'in' },
      { topNote: 12, bottomNote: 8, duration: 0.5, word: 'a' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'one' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'horse' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'op-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'en' },
      { topNote: 10, bottomNote: 7, duration: 2, word: 'sleigh' },
      { topNote: 15, bottomNote: '-', duration: 2, word: 'hey' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'gle' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'bells' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'gle' },
      { topNote: 12, bottomNote: 8, duration: 2, word: 'bells' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'jin-' },
      { topNote: 15, bottomNote: 12, duration: 1, word: 'gle' },
      { topNote: 8, bottomNote: 5, duration: 1.5, word: 'all' },
      { topNote: 10, bottomNote: 7, duration: 0.5, word: 'the' },
      { topNote: 12, bottomNote: 8, duration: 4, word: 'way' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'oh' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'what' },
      { topNote: 13, bottomNote: 10, duration: 1.5, word: 'fun' },
      { topNote: 13, bottomNote: 10, duration: 0.5, word: 'it' },
      { topNote: 13, bottomNote: 10, duration: 1, word: 'is' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'to' },
      { topNote: 12, bottomNote: 8, duration: 1, word: 'ride' },
      { topNote: 12, bottomNote: 8, duration: 0.5, word: 'in' },
      { topNote: 12, bottomNote: 8, duration: 0.5, word: 'a' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'one' },
      { topNote: 15, bottomNote: 7, duration: 1, word: 'horse' },
      { topNote: 13, bottomNote: 7, duration: 1, word: 'o-' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'pen' },
      { topNote: 8, bottomNote: '-', duration: 4, word: 'sleigh' },
    ]
  },
  "I heard the bells": {
    timeSignature: 4,
    defaultBPM: 80,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: 6, bottomNote: '-', duration: 1, word: 'I', lineBreak: true },
      { topNote: 10, bottomNote: 6, duration: 1.5, word: 'heard' },
      { topNote: 9, bottomNote: 8, duration: 0.5, word: 'the' },
      { topNote: 10, bottomNote: 6, duration: 1, word: 'bells' },
      { topNote: 10, bottomNote: 4, duration: 1, word: 'on' },
      { topNote: 11, bottomNote: 5, duration: 1.5, word: 'Christ-' },
      { topNote: 10, bottomNote: 5, duration: 0.5, word: 'mas' },
      { topNote: 11, bottomNote: 5, duration: 1, word: 'day' },
      { topNote: 12, bottomNote: 6, duration: 1, word: 'Their' },
      { topNote: 13, bottomNote: 6, duration: 1, word: 'old' },
      { topNote: 10, bottomNote: '-', duration: 1, word: 'fa-' },
      { topNote: 17, bottomNote: 10, duration: 1, word: 'mil-' },
      { topNote: 15, bottomNote: 6, duration: 1, word: 'iar' },
      { topNote: 15, bottomNote: 8, duration: 1.5, word: 'car-' },
      { topNote: 13, bottomNote: 8, duration: 0.5, word: 'ols' },
      { topNote: 13, bottomNote: 8, duration: 1, word: 'play' },
      { topNote: 13, bottomNote: 6, duration: 1, word: 'And' },
      { topNote: 13, bottomNote: 6, duration: 1.5, word: 'wild' },
      { topNote: 11, bottomNote: 6, duration: 0.5, word: 'and' },
      { topNote: 10, bottomNote: 6, duration: 1, word: 'sweet' },
      { topNote: 11, bottomNote: 1, duration: 1, word: 'the' },
      { topNote: 10, bottomNote: 2, duration: 1.5, word: 'words' },
      { topNote: 8, bottomNote: 2, duration: 0.5, word: 're-' },
      { topNote: 6, bottomNote: 3, duration: 1, word: 'peat' },
      { topNote: 8, bottomNote: 6, duration: 1, word: 'Of' },
      { topNote: 10, bottomNote: 6, duration: 1, word: 'peace' },
      { topNote: 11, bottomNote: 6, duration: 1, word: 'on' },
      { topNote: 13, bottomNote: 6, duration: 1, word: 'earth' },
      { topNote: 15, bottomNote: 6, duration: 1, word: 'good' },
      { topNote: 5, bottomNote: '-', duration: 1.5, word: 'will' },
      { topNote: 8, bottomNote: 5, duration: 0.5, word: 'to' },
      { topNote: 6, bottomNote: '-', duration: 1, word: 'men' },
    ]
  },
  "Away in a manger (1)": {
    timeSignature: 3,
    defaultBPM: 85,
    notes: [
      // Count off
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: '-', bottomNote: '-', duration: 1 },
      { topNote: 17, bottomNote: 14, duration: 1, word: 'A-', lineBreak: true },
      { topNote: 17, bottomNote: 14, duration: 1.5, word: 'way' },
      { topNote: 15, bottomNote: 12, duration: 0.5, word: 'in' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'a' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'man-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'ger' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'no' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'crib' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'for' },
      { topNote: 7, bottomNote: 3, duration: 1, word: 'his' },
      { topNote: 5, bottomNote: 2, duration: 2, word: 'bed' },
      { topNote: 5, bottomNote: 2, duration: 1, word: 'The' },
      { topNote: 5, bottomNote: 3, duration: 1.5, word: 'lit-' },
      { topNote: 7, bottomNote: 3, duration: 0.5, word: 'tle' },
      { topNote: 5, bottomNote: 3, duration: 1, word: 'Lord' },
      { topNote: 5, bottomNote: 3, duration: 1, word: 'Je-' },
      { topNote: 12, bottomNote: 3, duration: 1, word: 'sus' },
      { topNote: 9, bottomNote: 3, duration: 1, word: 'laid' },
      { topNote: 7, bottomNote: 3, duration: 1, word: 'down' },
      { topNote: 5, bottomNote: 2, duration: 1, word: 'his' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'sweet' },
      { topNote: 14, bottomNote: 10, duration: 2, word: 'head' },
      { topNote: 17, bottomNote: 14, duration: 1, word: 'The' },
      { topNote: 17, bottomNote: 14, duration: 1.5, word: 'stars' },
      { topNote: 15, bottomNote: 12, duration: 0.5, word: 'in' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'The' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'hea-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'ven' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'looked' },
      { topNote: 10, bottomNote: 7, duration: 1, word: 'down' },
      { topNote: 9, bottomNote: 5, duration: 1, word: 'where' },
      { topNote: 7, bottomNote: 3, duration: 1, word: 'he' },
      { topNote: 5, bottomNote: 2, duration: 2, word: 'lay' },
      { topNote: 5, bottomNote: 2, duration: 1, word: 'The' },
      { topNote: 15, bottomNote: 9, duration: 1.5, word: 'li-' },
      { topNote: 14, bottomNote: 9, duration: 0.5, word: 'tle' },
      { topNote: 12, bottomNote: 9, duration: 1, word: 'Lord' },
      { topNote: 14, bottomNote: 10, duration: 1, word: 'Je-' },
      { topNote: 12, bottomNote: 5, duration: 1, word: 'sus' },
      { topNote: 10, bottomNote: 5, duration: 1, word: 'a-' },
      { topNote: 12, bottomNote: 7, duration: 1, word: 'sleep' },
      { topNote: 7, bottomNote: 3, duration: 1, word: 'on' },
      { topNote: 9, bottomNote: 3, duration: 1, word: 'the' },
      { topNote: 10, bottomNote: 2, duration: 2, word: 'hay' },
    ]
  },
  "Silent Night / Peace": {
    timeSignature: 6,
    defaultBPM: 120,
    notes: [
      // Count off
      { notes: ['-', '-', '-'], duration: 1 },
      { notes: ['-', '-', '-'], duration: 1 },
      { notes: ['-', '-', '-'], duration: 1, lineBreak: true },
      // Peace intro
      { notes: ['-', '-', 13], duration: 3, word: 'Peace,' },
      { notes: ['-', '-', 12], duration: 3, word: 'peace,' },
      { notes: ['-', '-', 10], duration: 2, word: 'peace' },
      { notes: ['-', '-', 10], duration: 1, word: 'on' },
      { notes: ['-', '-', 8], duration: 1, word: 'ea-' },
      { notes: ['-', '-', 13], duration: 1, word: 'rth' },
      { notes: ['-', '-', 10], duration: 1, word: 'and' },
      { notes: ['-', '-', 12], duration: 3, word: 'good' },
      { notes: ['-', '-', 8], duration: 1, word: 'will' },
      { notes: ['-', '-', 10], duration: 1, word: '-' },
      { notes: ['-', '-', 12], duration: 1, word: 'to' },
      { notes: ['-', '-', 13], duration: 3, word: 'all!' },
      { notes: ['-', '-', 5], duration: 1, word: 'This' },
      { notes: ['-', '-', 6], duration: 1, word: 'is' },
      { notes: ['-', '-', 8], duration: 1, word: 'a' },
      { notes: ['-', '-', 6], duration: 3, word: 'time' },
      { notes: ['-', '-', 10], duration: 3, word: 'for' },
      { notes: ['-', '-', 5], duration: 3, word: 'joy.' },
      { notes: ['-', '-', 8], duration: 1, word: 'This' },
      { notes: ['-', '-', 6], duration: 1, word: 'is' },
      { notes: ['-', '-', 5], duration: 1, word: 'a' },
      { notes: ['-', '-', 6], duration: 3, word: 'time' },
      { notes: ['-', '-', 10], duration: 3, word: 'for' },
      { notes: ['-', '-', 5], duration: 3, word: 'love.' },
      { notes: ['-', '-', 8], duration: 1, word: 'Now' },
      { notes: ['-', '-', 13], duration: 1, word: 'let' },
      { notes: ['-', '-', 10], duration: 1, word: 'us' },
      { notes: ['-', '-', 12], duration: 3, word: 'all' },
      { notes: ['-', '-', 8], duration: 2, word: 'sing' },
      { notes: ['-', '-', 6], duration: 1, word: 'to-' },
      { notes: ['-', '-', 5], duration: 3, word: 'ge-' },
      { notes: ['-', '-', 13], duration: 2, word: 'ther' },
      { notes: ['-', '-', 10], duration: 1, word: 'of' },
      { notes: ['-', '-', 8], duration: 3, word: 'peace,' },
      { notes: ['-', '-', 12], duration: 3, word: 'peace,' },
      { notes: ['-', '-', 13], duration: 1, word: 'pea-' },
      { notes: ['-', '-', 8], duration: 1, word: 'ce' },
      { notes: ['-', '-', 6], duration: 1, word: 'on' },
      { notes: ['-', '-', 5], duration: 3, word: 'earth!' },
      // Silent Night (2 parts)
      { notes: [8, 5, '-'], duration: 1.5, word: 'Si-' },
      { notes: [10, 6, '-'], duration: 0.5, word: '-' },
      { notes: [8, 5, '-'], duration: 1, word: 'lent' },
      { notes: [5, 1, '-'], duration: 3, word: 'night!' },
      { notes: [8, 5, '-'], duration: 1.5, word: 'Ho-' },
      { notes: [10, 6, '-'], duration: 0.5, word: '-' },
      { notes: [8, 5, '-'], duration: 1, word: 'ly' },
      { notes: [5, 1, '-'], duration: 3, word: 'night!' },
      { notes: [15, 6, '-'], duration: 2, word: 'All' },
      { notes: [15, 6, '-'], duration: 1, word: 'is' },
      { notes: [12, 3, '-'], duration: 3, word: 'calm,' },
      { notes: [13, 5, '-'], duration: 2, word: 'all' },
      { notes: [13, 5, '-'], duration: 1, word: 'is' },
      { notes: [8, 5, '-'], duration: 3, word: 'bright!' },
      { notes: [10, 6, '-'], duration: 2, word: 'Round' },
      { notes: [10, 6, '-'], duration: 1, word: 'yon' },
      { notes: [13, 10, '-'], duration: 1.5, word: 'vir-' },
      { notes: [12, 8, '-'], duration: 0.5, word: '-' },
      { notes: [10, 6, '-'], duration: 1, word: 'gin' },
      { notes: [8, 5, '-'], duration: 1.5, word: 'mo-' },
      { notes: [10, 6, '-'], duration: 0.5, word: 'ther' },
      { notes: [8, 5, '-'], duration: 1, word: 'and' },
      { notes: [5, 1, '-'], duration: 3, word: 'child.' },
      { notes: [10, 1, '-'], duration: 2, word: 'Ho-' },
      { notes: [10, 6, '-'], duration: 1, word: 'ly' },
      { notes: [13, 10, '-'], duration: 1.5, word: 'In-' },
      { notes: [12, 8, '-'], duration: 0.5, word: 'fant' },
      { notes: [10, 6, '-'], duration: 1, word: 'so' },
      { notes: [8, 5, '-'], duration: 1.5, word: 'ten-' },
      { notes: [10, 6, '-'], duration: 0.5, word: 'der' },
      { notes: [8, 5, '-'], duration: 1, word: 'and' },
      { notes: [5, 1, '-'], duration: 3, word: 'mild,' },
      { notes: [15, 6, '-'], duration: 2, word: 'sleep' },
      { notes: [15, 6, '-'], duration: 1, word: 'in' },
      { notes: [18, 6, '-'], duration: 1.5, word: 'hea-' },
      { notes: [15, 6, '-'], duration: 0.5, word: 'ven-' },
      { notes: [12, 6, '-'], duration: 1, word: 'ly' },
      { notes: [13, 5, '-'], duration: 3, word: 'pea-' },
      { notes: [17, 8, '-'], duration: 3, word: '-ce!' },
      { notes: [13, 5, '-'], duration: 1.5, word: 'Sle-' },
      { notes: [8, '-', '-'], duration: 0.5, word: 'ep' },
      { notes: [5, 1, '-'], duration: 1, word: 'in' },
      { notes: [8, 5, '-'], duration: 1.5, word: 'hea-' },
      { notes: [6, 3, '-'], duration: 0.5, word: 'ven-' },
      { notes: [3, '-', '-'], duration: 1, word: 'ly' },
      { notes: [1, '-', '-'], duration: 6, word: 'peace!' },
      // Silent Night (3 parts with harmony)
      { notes: [8, 5, 13], duration: 1.5, word: 'Si-' },
      { notes: [10, 6, '-'], duration: 0.5, word: '-' },
      { notes: [8, 5, '-'], duration: 1, word: 'lent' },
      { notes: [5, 1, 12], duration: 3, word: 'night!' },
      { notes: [8, 5, 10], duration: 1.5, word: 'Ho-' },
      { notes: [10, 6, '-'], duration: 0.5, word: '-' },
      { notes: [8, 5, 10], duration: 1, word: 'ly' },
      { notes: [5, 1, 8], duration: 1, word: 'night!' },
      { notes: ['-', '-', 13], duration: 1, word: '~' },
      { notes: ['-', '-', 10], duration: 1, word: '~' },
      { notes: [15, 6, 12], duration: 2, word: 'All' },
      { notes: [15, 6, '-'], duration: 1, word: 'is' },
      { notes: [12, 3, 8], duration: 1, word: 'calm,' },
      { notes: ['-', '-', 10], duration: 1, word: '~' },
      { notes: ['-', '-', 12], duration: 1, word: '~' },
      { notes: [13, 5, 13], duration: 2, word: 'all' },
      { notes: [13, 5, '-'], duration: 1, word: 'is' },
      { notes: [8, '-', 5], duration: 1, word: 'bright!' },
      { notes: ['-', '-', 6], duration: 1, word: '~' },
      { notes: ['-', '-', 8], duration: 1, word: '~' },
      { notes: [10, 6, 6], duration: 2, word: 'Round' },
      { notes: [10, 6, '-'], duration: 1, word: 'yon' },
      { notes: [13, '-', 10], duration: 1.5, word: 'vir-' },
      { notes: [12, 8, '-'], duration: 0.5, word: '-' },
      { notes: [10, 6, '-'], duration: 1, word: 'gin' },
      { notes: [8, '-', 5], duration: 1.5, word: 'mo-' },
      { notes: [10, 6, '-'], duration: 0.5, word: 'ther' },
      { notes: [8, 5, '-'], duration: 1, word: 'and' },
      { notes: [5, 1, 8], duration: 1, word: 'child.' },
      { notes: ['-', '-', 6], duration: 1, word: '~' },
      { notes: ['-', '-', 5], duration: 1, word: '~' },
      { notes: [10, 1, 6], duration: 2, word: 'Ho-' },
      { notes: [10, 6, '-'], duration: 1, word: 'ly' },
      { notes: [13, '-', 10], duration: 1.5, word: 'In-' },
      { notes: [12, 8, '-'], duration: 0.5, word: 'fant' },
      { notes: [10, 6, '-'], duration: 1, word: 'so' },
      { notes: [8, 5, 5], duration: 1.5, word: 'ten-' },
      { notes: [10, 6, '-'], duration: 0.5, word: 'der' },
      { notes: [8, 5, '-'], duration: 1, word: 'and' },
      { notes: [5, 1, 8], duration: 1, word: 'mild,' },
      { notes: ['-', '-', 13], duration: 1, word: '~' },
      { notes: ['-', '-', 10], duration: 1, word: '~' },
      { notes: [15, 6, 12], duration: 2, word: 'sleep' },
      { notes: [15, 6, '-'], duration: 1, word: 'in' },
      { notes: [18, 6, 8], duration: 1.5, word: 'hea-' },
      { notes: [15, 6, '-'], duration: 0.5, word: 'ven-' },
      { notes: [12, '-', 6], duration: 1, word: 'ly' },
      { notes: [13, '-', 5], duration: 3, word: 'pea-' },
      { notes: [17, 8, 13], duration: 2, word: '-ce!' },
      { notes: ['-', '-', 10], duration: 1, word: '~' },
      { notes: [13, 5, 8], duration: 1.5, word: 'Sle-' },
      { notes: [8, '-', '-'], duration: 0.5, word: 'ep' },
      { notes: [5, 1, '-'], duration: 1, word: 'in' },
      { notes: [8, 5, 12], duration: 1.5, word: 'hea-' },
      { notes: [6, 3, '-'], duration: 0.5, word: 'ven-' },
      { notes: [3, '-', '-'], duration: 1, word: 'ly' },
      { notes: [1, '-', 13], duration: 1, word: 'peace!' },
      { notes: ['-', '-', 8], duration: 1, word: '~' },
      { notes: ['-', '-', 6], duration: 1, word: '~' },
      { notes: ['-', '-', 5], duration: 3, word: '~' },
    ]
  }

};
